Acme\PmeBundle\Entity\Tauxtva:
  type: entity
  repositoryClass: Acme\PmeBundle\Entity\Repository\TauxtvaRepository   
  table: pme_tauxtva
  fields:
    id:
      id: true
      type: integer
      generator:
        strategy: AUTO
    taux:
      type: decimal
      precision: 10
      scale: 2      
  lifecycleCallbacks: {  }