acme_pme:
    resource: "@AcmePmeBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: @AppBundle/Controller/
    type:     annotation
    
_pme_login:
    pattern:   /login
    defaults:  { _controller: AcmePmeBundle:Secured:login }
    
_security_check:
    pattern:   /login_check    
    
_pme_logout:
    pattern:   /logout
    defaults:  { _controller: AcmePmeBundle:Default:logout }       
