contacts:
    path:     /
    defaults: { _controller: "AcmePmeBundle:Contacts:index" }

contacts_show:
    path:     /{id}/show
    defaults: { _controller: "AcmePmeBundle:Contacts:show" }

contacts_new:
    path:     /new
    defaults: { _controller: "AcmePmeBundle:Contacts:new" }

contacts_create:
    path:     /create
    defaults: { _controller: "AcmePmeBundle:Contacts:create" }
    requirements: { _method: post }

contacts_edit:
    path:     /{id}/edit
    defaults: { _controller: "AcmePmeBundle:Contacts:edit" }

contacts_update:
    path:     /{id}/update
    defaults: { _controller: "AcmePmeBundle:Contacts:update" }
    requirements: { _method: post|put }

contacts_delete:
    path:     /{id}/delete
    defaults: { _controller: "AcmePmeBundle:Contacts:delete" }
    requirements: { _method: post|delete }
