#acme_pme_homepage:
#    path:     /hello/{name}
#    defaults: { _controller: AcmePmeBundle:Default:index }
    
acme_pme_homepage:
    resource: "@AcmePmeBundle/Controller/DefaultController.php"
    type:   annotation
    
acme_pme_referents:
    resource: "@AcmePmeBundle/Controller/ReferentsController.php"
    type:   annotation
    
acme_pme_organisations:
    resource: "@AcmePmeBundle/Controller/OrganisationsController.php"
    type:   annotation    
    
acme_pme_devis:
    resource: "@AcmePmeBundle/Controller/DevisController.php"
    type:   annotation     
    
acme_pme_contacts:
    resource: "@AcmePmeBundle/Controller/ContactsController.php"
    type:   annotation 
    
acme_pme_taux_tva:
    resource: "@AcmePmeBundle/Controller/TauxtvaController.php"
    type:   annotation 
    
acme_pme_services:
    resource: "@AcmePmeBundle/Controller/ServicesController.php"
    type:   annotation     
    
acme_pme_statuts:
    resource: "@AcmePmeBundle/Controller/StatutsController.php"
    type:   annotation    
    
acme_pme_centres_interet:
    resource: "@AcmePmeBundle/Controller/CentresinteretController.php"
    type:   annotation   
    
acme_pme_villes:
    resource: "@AcmePmeBundle/Controller/VillesController.php"
    type:   annotation     
    
acme_pme_commandes:
    resource: "@AcmePmeBundle/Controller/CommandesController.php"
    type:   annotation     
    
acme_pme_produits:
    resource: "@AcmePmeBundle/Controller/ProduitsController.php"
    type:   annotation     
    
acme_pme_modeles_courriers:
    resource: "@AcmePmeBundle/Controller/ModelescourriersController.php"
    type:   annotation 
    
acme_pme_adresses_livraisons_facturations:
    resource: "@AcmePmeBundle/Controller/AdresseslivraisonsfacturationsController.php"
    type:   annotation  
    
acme_pme_messages:
    resource: "@AcmePmeBundle/Controller/MessagesController.php"
    type:   annotation      