<?php

namespace Acme\PmeBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PaysRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaysRepository extends EntityRepository
{
}
