<?php

namespace Acme\PmeBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TypesactionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypesactionRepository extends EntityRepository
{
}
